[package]
name = "pixy"
version = "0.1.2"
edition = "2024"
description = "Fast Lua-powered terminal renderer"
license = "MIT"
readme = "README.md"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
flate2 = "1"
libc = "0.2"
luna = { git = "https://github.com/onix-os/luna", rev = "8b370fc7975cc9a3fbf18c07d9250d63aa2bbca6" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
unicode-width = "0.2"
wait-timeout = "0.2"

[dev-dependencies]

[build-dependencies]
flate2 = "1"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
strip = "symbols"

[profile.dev.package.luna]
opt-level = 3

[profile.dev.package.ottavino-gc-arena]
opt-level = 3
