#!/usr/bin/env bash
# Turns text files into C string literals: the bundled Lua modules, the default
# config and the shell integrations all ship inside the binary.
#
#   scripts/embed_text.sh modules  build/lua_modules.c   lua/pixy/...
#   scripts/embed_text.sh text     build/texts.c         NAME=path ...
set -euo pipefail

mode=$1
output=$2
shift 2

# A C string literal per line keeps the generated file readable and sidesteps
# the 64 KiB limit some compilers put on a single literal.
emit_literal() {
  local file=$1
  awk '
    {
      line = $0
      gsub(/\\/, "\\\\", line)
      gsub(/"/, "\\\"", line)
      gsub(/\t/, "\\t", line)
      printf "    \"%s\\n\"\n", line
    }
    END { if (NR == 0) printf "    \"\"\n" }
  ' "$file"
}

{
  printf '/* Generated by scripts/embed_text.sh. Do not edit. */\n'
  printf '#include <stddef.h>\n\n'

  if [ "$mode" = modules ]; then
    printf '#include "engine.h"\n\n'
    index=0
    for path in "$@"; do
      printf 'static const char module_%d[] =\n' "$index"
      emit_literal "$path"
      printf ';\n\n'
      index=$((index + 1))
    done

    printf 'const PixyModule PIXY_MODULES[] = {\n'
    index=0
    for path in "$@"; do
      # lua/pixy/segments/git.lua -> pixy.segments.git
      name=${path#lua/}
      name=${name%.lua}
      name=${name%/init}
      name=${name//\//.}
      printf '    {"%s", module_%d, sizeof(module_%d) - 1},\n' "$name" "$index" "$index"
      index=$((index + 1))
    done
    printf '};\n'
    printf 'const size_t PIXY_MODULE_COUNT = %d;\n' "$index"
  else
    for pair in "$@"; do
      symbol=${pair%%=*}
      path=${pair#*=}
      printf 'const char %s[] =\n' "$symbol"
      emit_literal "$path"
      printf ';\n\n'
    done
  fi
} >"$output"
