/* Compiles the bundled Lua modules at build time.
 *
 *   lua_precompile build/lua_modules.c lua/pixy/init.lua ...
 *
 * Parsing 64KB of Lua source took ~1ms of a ~2ms prompt, every prompt, to
 * arrive at exactly the same functions each time. Doing it once here and
 * shipping the result costs ~0.1ms to load instead.
 *
 * The source is emitted too. Bytecode is specific to the architecture and the
 * Lua build that produced it, so a binary compiled for a machine this tool
 * cannot run on would otherwise have no way to start at all; the engine falls
 * back to the source when the bytecode is not loadable here.
 *
 * Debug information is deliberately kept: the chunk name and line numbers are
 * what a configuration error quotes, and those messages are pinned by tests.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "lauxlib.h"
#include "lua.h"
#include "lualib.h"

typedef struct {
    unsigned char *bytes;
    size_t len;
    size_t capacity;
} Blob;

static int collect(lua_State *L, const void *chunk, size_t size, void *ud) {
    (void)L;
    Blob *blob = ud;
    if (blob->len + size > blob->capacity) {
        size_t wanted = (blob->len + size) * 2;
        unsigned char *grown = realloc(blob->bytes, wanted);
        if (!grown) return 1;
        blob->bytes = grown;
        blob->capacity = wanted;
    }
    memcpy(blob->bytes + blob->len, chunk, size);
    blob->len += size;
    return 0;
}

/* lua/pixy/segments/git.lua -> pixy.segments.git */
static void module_name(const char *path, char *out, size_t size) {
    const char *at = strncmp(path, "lua/", 4) == 0 ? path + 4 : path;
    snprintf(out, size, "%s", at);
    char *dot = strrchr(out, '.');
    if (dot && strcmp(dot, ".lua") == 0) *dot = '\0';
    size_t len = strlen(out);
    if (len > 5 && strcmp(out + len - 5, "/init") == 0) out[len - 5] = '\0';
    for (char *scan = out; *scan; scan++) {
        if (*scan == '/') *scan = '.';
    }
}

static char *read_file(const char *path, size_t *len_out) {
    FILE *file = fopen(path, "rb");
    if (!file) return NULL;
    fseek(file, 0, SEEK_END);
    long size = ftell(file);
    fseek(file, 0, SEEK_SET);
    if (size < 0) {
        fclose(file);
        return NULL;
    }
    char *text = malloc((size_t)size + 1);
    if (!text) {
        fclose(file);
        return NULL;
    }
    size_t got = fread(text, 1, (size_t)size, file);
    fclose(file);
    text[got] = '\0';
    *len_out = got;
    return text;
}

static void emit_bytes(FILE *out, const unsigned char *bytes, size_t len) {
    for (size_t i = 0; i < len; i++) {
        fprintf(out, "%s0x%02x,", i % 16 == 0 ? "\n    " : "", bytes[i]);
    }
    fprintf(out, "\n");
}

/* One C string literal per line: readable, and under the 64KiB literal limit
 * some compilers hold to. */
static void emit_source(FILE *out, const char *text, size_t len) {
    fprintf(out, "    \"");
    for (size_t i = 0; i < len; i++) {
        switch (text[i]) {
        case '\\':
            fprintf(out, "\\\\");
            break;
        case '"':
            fprintf(out, "\\\"");
            break;
        case '\t':
            fprintf(out, "\\t");
            break;
        case '\n':
            fprintf(out, "\\n\"\n    \"");
            break;
        default:
            fputc(text[i], out);
            break;
        }
    }
    fprintf(out, "\"\n");
}

int main(int argc, char **argv) {
    if (argc < 3) {
        fprintf(stderr, "usage: lua_precompile <output.c> <module.lua>...\n");
        return 2;
    }
    FILE *out = fopen(argv[1], "wb");
    if (!out) {
        fprintf(stderr, "lua_precompile: cannot write %s\n", argv[1]);
        return 1;
    }
    lua_State *L = luaL_newstate();
    if (!L) return 1;
    luaL_openlibs(L);

    fprintf(out, "/* Generated by scripts/lua_precompile.c. Do not edit. */\n");
    fprintf(out, "#include <stddef.h>\n\n#include \"engine.h\"\n\n");

    int count = argc - 2;
    size_t source_total = 0, code_total = 0;
    for (int i = 0; i < count; i++) {
        const char *path = argv[i + 2];
        size_t len = 0;
        char *text = read_file(path, &len);
        if (!text) {
            fprintf(stderr, "lua_precompile: cannot read %s\n", path);
            return 1;
        }
        char name[256];
        module_name(path, name, sizeof(name));
        char chunk[300];
        snprintf(chunk, sizeof(chunk), "@bundled/%s.lua", name);

        if (luaL_loadbuffer(L, text, len, chunk) != LUA_OK) {
            fprintf(stderr, "lua_precompile: %s: %s\n", path, lua_tostring(L, -1));
            return 1;
        }
        Blob blob = {0};
        if (lua_dump(L, collect, &blob, 0) != 0) {
            fprintf(stderr, "lua_precompile: cannot dump %s\n", path);
            return 1;
        }
        lua_pop(L, 1);

        fprintf(out, "static const unsigned char code_%d[] = {", i);
        emit_bytes(out, blob.bytes, blob.len);
        fprintf(out, "};\n\nstatic const char source_%d[] =\n", i);
        emit_source(out, text, len);
        fprintf(out, ";\n\n");

        source_total += len;
        code_total += blob.len;
        free(blob.bytes);
        free(text);
    }

    fprintf(out, "const PixyModule PIXY_MODULES[] = {\n");
    for (int i = 0; i < count; i++) {
        char name[256];
        module_name(argv[i + 2], name, sizeof(name));
        fprintf(out, "    {\"%s\", source_%d, sizeof(source_%d) - 1, code_%d, sizeof(code_%d)},\n",
                name, i, i, i, i);
    }
    fprintf(out, "};\nconst size_t PIXY_MODULE_COUNT = %d;\n", count);
    fclose(out);
    lua_close(L);

    fprintf(stderr, "lua_precompile: %d modules, %zu bytes of source, %zu of bytecode\n", count,
            source_total, code_total);
    return 0;
}
